Mera/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("currency_rate.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

currency_rate/urls.py
from django.urls import path
from .views import *

app_name = "currency_rate"

urlpatterns = [
    path("", index),
    path(
        "api/get_currencies_data_by_period",
        get_currencies_data_by_period.as_view(),
        name="get_currencies_data_by_period",
    ),
]

currency_rate/models.py
from django.db import models
from django.core.validators import MinValueValidator


class BtcRecords(models.Model):
    """
        Модель для хранения финансовой информации
    """

    calculation_date = models.DateTimeField("Дата Расчета")

    btc_price = models.DecimalField(
        "Курс Биткойна",
        decimal_places=2,
        max_digits=12,
        validators=[MinValueValidator(0)],
    )

    assets_price = models.DecimalField(
        "Стоимость чистых активов",
        decimal_places=2,
        max_digits=12,
        validators=[MinValueValidator(0)],
    )

    pnl = models.DecimalField(
        "Текущиий PnL",
        decimal_places=2,
        max_digits=12,
    )

    index_pnl = models.FloatField("Текущий Index PnL")

currency_rate/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from datetime import datetime
from .models import *
from django.utils import timezone


def index(request):
    """
    Вьюха, возвращающая главную страницу
    """
    return render(request, "index.html")


class get_currencies_data_by_period(APIView):
    """
    REST-API Вьюха, которая получает в параметрах GET-запроса начало и конец временного периода
     и отдает pnl, pnl_%, index_pnl
    """

    def get(self, request, format=None):
        datetime_format_string = "%Y_%m_%d_%H_%M_%S"
        tz = timezone.get_current_timezone()

        try:
            period_start = request.query_params.get("period_start")
            if period_start:
                period_start = datetime.strptime(
                    period_start, datetime_format_string
                ).replace(tzinfo=tz)

            period_end = request.query_params.get("period_end")
            if period_end:
                period_end = datetime.strptime(
                    period_end, datetime_format_string
                ).replace(tzinfo=tz)

        except Exception:
            return Response(data="Wrong parameters", status=status.HTTP_400_BAD_REQUEST)

        records = BtcRecords.objects.all()

        if period_start:
            records = records.filter(calculation_date__gte=period_start)
        if period_end:
            records = records.filter(calculation_date__lte=period_end)

        if not records:
            return Response(data="Not Found", status=status.HTTP_404_NOT_FOUND)

        first_record = records.first()
        last_record = records.last()

        return Response(
            {
                "pnl": last_record.assets_price - first_record.assets_price,
                "pnl_%": round(
                    (last_record.assets_price / first_record.assets_price - 1) * 100, 5
                ),
                "index_pnl": round(
                    last_record.assets_price / first_record.assets_price, 5
                ),
            }
        )

templates/index.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Расчет финансовых показателей</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" />
    </head>
    <body style="margin: 40px; font-size: 20px;">
        <div class="container1" style="display: flex; flex-direction: column; align-items: flex-start;">
            <h1 class="page-header">Расчет финансовых показателей</h1>

            <div class="container2" style="display: flex; flex-direction: row; align-items: center;">
                <div class="menu">
                    <div class="row">
                        <div class="col-xs-12">
                            <h2>C какого времени</h2>
                            <input type="text" class="form-control" id="datetimepicker1" />
                            <h5>Оставьте пустым чтобы не ставить нижнюю границу</h5>
                            <h2>По какое время</h2>
                            <input type="text" class="form-control" id="datetimepicker2" />
                            <h5>Оставьте пустым чтобы не ставить верхнюю границу</h5>
                        </div>
                    </div>
                    <button type="button" style="margin-top: 20px;" class="btn btn-primary" id="confirm_calculation" ;>Расчитать</button>
                </div>
                <div>
                    <table class="table" style="margin-left: 100; font-size: 26; margin-top: 35;">
                        <tbody>
                            <tr>
                                <th scope="row">PnL</th>
                                <td id="pnlValue"></td>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="row">PnL %,</th>
                                <td id="pnlPercValue"></td>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="row">Index PnL</th>
                                <td id="indexpnlValue"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/moment-with-locales.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
        <script type="text/javascript">
            $(function () {
                $("#datetimepicker1").datetimepicker({
                    locale: "ru",
                    format: "YYYY/MM/DD HH:mm:ss",
                });
                $("#datetimepicker2").datetimepicker({
                    locale: "ru",
                    format: "YYYY/MM/DD HH:mm:ss",
                });
            });
        </script>

        <script type="text/javascript">
            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== "") {
                    const cookies = document.cookie.split(";");
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === name + "=") {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            function normalizeDatetime(dateTime) {
                dateTime = dateTime.split(" ");

                date = dateTime[0].replaceAll("/", "_");

                time = dateTime[1].replaceAll(":", "_");
                normalizedDateTime = date + "_" + time;
                return normalizedDateTime;
            }

            document.getElementById("confirm_calculation").onclick = function () {
                const csrfToken = getCookie("csrftoken");
                let url = "{% url 'currency_rate:get_currencies_data_by_period' %}";
                let startDate = document.getElementById("datetimepicker1").value;
                if (startDate) {
                    startDate = normalizeDatetime(startDate);
                }

                let endDate = document.getElementById("datetimepicker2").value;
                if (endDate) {
                    endDate = normalizeDatetime(endDate);
                }

                let params = "";

                if (endDate && startDate) {
                    params += "?period_start=" + startDate + "&period_end=" + endDate;
                } else if (startDate) {
                    params += "?period_start=" + startDate;
                } else if (endDate) {
                    params += "?period_end=" + endDate;
                }
                url += params;
                let xhr = new XMLHttpRequest();
                xhr.open("GET", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.setRequestHeader("X-CSRFToken", csrfToken);
                xhr.onload = function () {
                    if (xhr.status == 404) {
                        alert('Не найдено информации за этот промежуток времени');
                    } else if (xhr.status == 200) {
                        $("#pnlValue").html(JSON.parse(xhr.responseText)["pnl"]);
                        $("#pnlPercValue").html(JSON.parse(xhr.responseText)["pnl_%"]);
                        $("#indexpnlValue").html(JSON.parse(xhr.responseText)["index_pnl"]);
                    }
                };
                xhr.send();
            };
        </script>
    </body>
</html>